name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*'
      - '!.github/workflows/release.yml'
      - '!app/package.json'
      - '!app/package-lock.json'
      - '!app/electron-builder.config.js'
      - '!app/src/vite_main.config.js'
      - '!app/src/vite_renderer.config.js'
      - '!app/src/scripts/*'
      - '!server/build_server.sh'
      - '!server/poetry.lock'
      - '!server/pyoxidizer.bzl'
      - '!server/pyproject.toml'
      - '!server/requirements.txt'


concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true


defaults:
  run:
    shell: 'bash'


jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.build-version }}
      branch: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get version from current date
        id: version
        run: echo "::set-output name=build-version::$(node -e "try{console.log(require('./app/electron-builder.config.js').extraMetadata.version)}catch(e){console.error(e);process.exit(1)}")"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Echo branch name
        shell: bash
        run: echo "Currently on branch '${{ steps.extract_branch.outputs.branch }}'"

  draft:
    runs-on: ubuntu-latest
    needs: [ get_version ]
    if: ${{ github.event_name == 'push' && needs.get_version.outputs.branch == 'main' }}
    steps:
      - name: Waiting on All checks
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: 'draft'

      - name: Delete outdated drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          prerelease: true
          draft: true
          tag_name: v${{ needs.get_version.outputs.version }}
          name: v${{ needs.get_versions.outputs.version }}
          body: a pre-release of audapolis

  upload_artifacts:
    name: Build version
    needs: [ get_version ]

    strategy:
      matrix:
        os: [ macos-10.15, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      # Build server
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
          key: ${{ runner.os }}-cargo

      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable

      - name: Install pyoxidizer fork
        run: cargo install --git https://github.com/audapolis/PyOxidizer.git --rev 3f3980d81e67928db83df20b9c1aefa3c8235866 pyoxidizer

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build
        run: ./server/build_server.sh
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm --prefix app/ ci

      # Compile app and upload artifacts
      - name: Compile & release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          VITE_APP_VERSION: ${{ needs.get_version.outputs.version }}
        with:
          build_script_name: build
          package_root: app/
          args: --config electron-builder.config.js

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is in the main branch and this does not run on a PR, release
          release: ${{ github.event_name == 'push' && needs.get_version.outputs.branch == 'main' }}

          # Sometimes the build may fail due to a connection problem with Apple, GitHub, etc. servers.
          # This option will restart the build as many attempts as possible
          max_attempts: 3


          # Code Signing params

          # Base64-encoded code signing certificate for Windows
          # windows_certs: ''

          # Password for decrypting `windows_certs`
          # windows_certs_password: ''

          # Base64-encoded code signing certificate for macOS
          # mac_certs: ''

          # Password for decrypting `mac_certs`
          # mac_certs_password: ''

  finalize:
    needs: [ upload_artifacts ]
    if: ${{ needs.upload_artifacts.result == 'skipped' || needs.upload_artifacts.result == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: No-op to pass
        shell: bash
        run: echo "Build succeeded"
